# Generated by Django 4.2.7 on 2023-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='학번')),
                ('phone_number', models.CharField(max_length=11, verbose_name='전화번호')),
                ('department', models.CharField(max_length=25, verbose_name='학과(부)')),
            ],
        ),
    ]
