# Generated by Django 4.2.7 on 2023-12-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='student_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='학번'),
        ),
    ]
