# Generated by Django 4.2.7 on 2023-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='모델 이름')),
                ('model_id', models.IntegerField(verbose_name='모델 번호')),
                ('is_available', models.BooleanField(verbose_name='대여 가능 여부')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='설명(사양 등)')),
            ],
            options={
                'unique_together': {('model_name', 'model_id')},
            },
        ),
    ]
