# Generated by Django 4.2.7 on 2023-12-03 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_available',
        ),
    ]
