# Generated by Django 4.2.7 on 2023-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20, verbose_name='건물 이름')),
                ('room', models.CharField(max_length=10, verbose_name='강의실 이름')),
                ('capacity', models.IntegerField(verbose_name='최대 수용 인원')),
                ('is_available', models.BooleanField(default=True, verbose_name='대여 가능 여부')),
            ],
            options={
                'unique_together': {('building', 'room')},
            },
        ),
    ]
