# Generated by Django 4.2.7 on 2023-12-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('devices', '0001_initial'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRecordOfDevice',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='대여 시작 정보')),
                ('end_date', models.DateTimeField(verbose_name='대여 반납 정보')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='대여한 장치')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceuser', verbose_name='대여자')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRecordOfClassroom',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='대여 시작 정보')),
                ('end_date', models.DateTimeField(verbose_name='대여 반납 정보')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom', verbose_name='대여한 강의실')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceuser', verbose_name='대여자')),
            ],
        ),
    ]
