# Generated by Django 4.2.7 on 2023-12-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('classrooms', '0002_remove_classroom_is_available'),
        ('devices', '0002_remove_device_is_available'),
        ('rental_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalRecordOfClassroom',
            new_name='ClassroomRentalRecord',
        ),
        migrations.RenameModel(
            old_name='RentalRecordOfDevice',
            new_name='DeviceRentalRecord',
        ),
    ]
